# Generated by Django 5.0.6 on 2024-05-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id_Tipo_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Tipo_Producto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Producto', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.stock')),
                ('Tipo_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tipo_producto')),
            ],
        ),
    ]
